### ISSUE TITLE
Incompatible with Valheim Plus

### ISSUE THREAD

**Issue by witherfox** [blaxxun-boop/PassivePowers#11]
This mod is incompatible with Valheim Plus

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose. If you get a message like this, the mod has been made incompatible by the mod author. Valheim Plus is a huge bully in the modding community and it needs to go.

Read https://github.com/blaxxun-boop/PassivePowers/issues/5 for more info.

**Comment by witherfox** [comment]
I understand that, but in the current state of the game, Valheim Plus comes preloaded with server host companies and it's become the cornerstone for most online servers and modded singleplayers. You are massively limiting your audience by refusing to make it compatible. Your mods won't last long in the community without it

**Comment by blaxxun-boop** [comment]
You are massively overestimating the importance of Valheim Plus. I have several mods that are more popular than Valheim Plus and I am not the only one adding incompatibilities with Valheim Plus to all my mods. Several other mod authors are doing the same and more and more are joining in.
You are massively underestimating how hated Valheim Plus is in the modding community. As I said, it's essentially a huge bully in the modding scene and pretty much every single modder is against it.

The only reason Valheim Plus became that popular in the first place is because they made some shady contracts with Valheim server hosters, which are now bound by the contracts and forcing Valheim Plus on their customers, if they want to play modded on their server. These contracts are about to end and we will make sure that they are not renewed. The philosophy of Valheim Plus is that they want to be the only mod that people use. They've said that multiple times. They do not care about compatibility with other mods, at all. They've bullied multiple people so much that they've stopped making mods for Valheim. Everyone that was around in the early days probably still remembers this. "Why are you making your own mods, instead of adding the code to Valheim Plus? If you don't stop this, we will simply copy your code into Valheim Plus and make it better." And that is how Valheim Plus became a jack of all trades, master of none kind of mod. It's essentially a collection of stolen ideas / code. I don't get how anyone could not understand that this is damaging the modding community a lot.
They even tried to hire people for money to write code for them. They wanted to monetize Valheim modding. But when Iron Gate killed the Valheim hype and it was clear that the Valheim community wouldn't stay as big as it was in the beginning, they've abandonded Valheim Plus. That's why someone completely unrelated to its creation is now keeping it on life support. Ridiculous.

It's easy to replace. Check https://github.com/AzumattDev/Valheim-Plus-Replacements and you will find that the replacement mods are waaay better than Valheim Plus will ever be.

**Comment by witherfox** [comment]
Wow, sounds like an absolute shit show over there at V+. Thank you so much for the info! I perged Valheim Plus from my server and replaced it's config with OdinsQoL. Even downloaded a good chunk of your library too :) It's exactly everything I needed. Thank you!
