### ISSUE TITLE
1.0.7 incompatible with ValheimPlus

### ISSUE THREAD

**Issue by LegalSmeagol** [blaxxun-boop/PassivePowers#5]
After yesterday's update, BepInEx is refusing to load PassivePowers with the following error message:

`[Error  :   BepInEx] Could not load [Passive Powers 1.0.7] because it is incompatible with: org.bepinex.plugins.valheim_plus`.

Downgrading to 1.0.6 is currently the only way to use this on a server running V+ (which I think is the vast majority of servers lol).

**Comment by blaxxun-boop** [comment]
Yes, this is on purpose. Moving forward, none of my mods will work with Valheim Plus and other mod authors will follow.

**Comment by LegalSmeagol** [comment]
Oh I see. Any particular reason why this is?

**Comment by blaxxun-boop** [comment]
We are just getting sick and tired of Valheim Plus. It's buggy as hell, not maintained anymore and forced down your throat with a lot of server hosters.
It's really deceitful at the same time as well, hiding its own stacktraces (you know, the huge red text in your log, of shit hits the fan) at some point and blaming other mods for issues. We are debugging issues with our mods on a daily basis, just to find out it's Valheim Plus which causes it. It's just not made with compatibility in mind, even if the authors like to claim otherwise.
Some of the issues I've reported to them will turn 2 years old soon. I provided clear instructions on how to fix them and they've promised to fix them as soon as possible, and yet here we are. So, that's usually just a lot of hot air, nothing else.
And there is nothing in Valheim Plus that cannot be easily replaced by another mod, which also happens to do it way better than Valheim Plus. It's a jack of all trades, master of none type of thing.

**Comment by LegalSmeagol** [comment]
Fair enough to be honest. I wonder if V+ might actually be causing a lot of our server desyncing/lag issues because by the sounds of it, it's a very hacked together mod. We'll see where we need replacement mods and yeet V+ asap.

Appreciate your hard and amazing work!

**Comment by blaxxun-boop** [comment]
Thanks for the kind words, I really appreciate it.

And I can assure you that while switching away from Valheim Plus is a lot of work, you will be much happier afterwards.
Think about it this way: Let's say you need two features. There is one mod that adds these two features, but also a third one that you don't plan on using. There are also two smaller mods that add one of the features you want each.
Some people are like "I want as few mods as possible", but that's the wrong approach. If you install the single mod, you have a 33% overhead, because it adds something you don't need. With the two small mods, you may have more mods installed, but less overhead.
Also, with smaller mods, they are way easier to replace or disable, if they break. A huge mod like Valheim Plus breaks with every Valheim update and you cannot simply disable it, if it breaks.

**Comment by SerpentDrago** [comment]
The main issue with this , and its one i'll just deal with (as i understand your argument) Vplus did so many minor little things . that no one would create a mod thats updated to do it as Vplus handled it . kinda a chicken and egg issue . 

I'm going to slowly switch my server away from vplus . painfull but it will be better overall . For now i'll roll back the version of passive powers i'm using

**Comment by killersassist** [comment]
Good to know about the shenanigans that come with Valheim Plus.  Any chance you could post on the Thunderstore page that versions past 1.06 are no longer compatible?  

Also thanks for a great mod.

**Comment by blaxxun-boop** [comment]
Check https://github.com/AzumattDev/Valheim-Plus-Replacements to find a list of mods to replace Valheim Plus.
