### ISSUE TITLE
Quick question about incompatibility with vplus 

### ISSUE THREAD

**Issue by SerpentDrago** [blaxxun-boop/PassivePowers#7]
does the mod now conflict with everything in Vplus or only if you enable specific aspects ? 

If only some aspects could we reach a compromise , and allow vplus usage as long as those parts of vplus are not enabled ? i know this could create its own support issue . but i would be willing to run a forked version and upload / manage it on thunderstore/github if its just a line of code to get it MOSTLY compatible.  

Now if its incompatible with every section of vplus then thats outside my ability and fully understand . 

as of NOW if i was to remove https://github.com/blaxxun-boop/PassivePowers/blob/0117e63e37e07f857e418ca14c6f9296d67c5c23/PassivePowers/PassivePowers.cs#L17

that line and compile / build the plugin , what would break ? depending on what is enabled in vplus ? Does it just cause issues with Totem buffs in vplus / etc etc 

Understand what i'm trying to say ? i noticed other mods that deal with powers / passive powers just tell others to Disable those sections of Vplus . 

This is the FINAL time i will post and "complain" about this decision , i just wanted to know . and try to reach some kinda in-between

**Comment by blaxxun-boop** [comment]
https://github.com/blaxxun-boop/PassivePowers/issues/5

Please note that no license on GitHub means "only looking, no touching".
If you want to keep using ValheimPlus, please simply remove all of my mods and all mods of other mod authors that are currently doing the same. The ValheimPlus devs will appreciate that, since they've said they want to be the only mod that people use since the early days of valheim modding. We are just helping them achieve their goal. 😉

Cheers.
